export enum AppointmentStatus {
  BOOKED = "BOOKED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  REJECTED_BY_PROVIDER = "REJECTED_BY_PROVIDER",
  NOT_ATTENDED = "NOT_ATTENDED",
  CONFIRMED = "CONFIRMED",
};
