export enum Role {
    ADMIN = "ADMIN",
    USER = "USER",
    PROVIDER = "PROVIDER",
};

export enum Boolean {
    TRUE = "true",
    FALSE = "false"
};

export enum FileType {
    PNG="image/png",
    JPEG="image/jpeg",
    JPG="image/jpg"
};

export enum Day {
    SUNDAY = "Sunday",
    MONDAY = "Monday",
    TUESDAY = "Tuesday",
    WEDNESDAY = "Wednesday",
    THURSDAY = "Thursday",
    FRIDAY = "Friday",
    SATURDAY = "Saturday",
};

export enum AppConnect {
    GOOGLE = "GOOGLE",
    STRIPE = "STRIPE",
    NOTION = "NOTION",
    WHATSAPP = "WHATSAPP",
    RAZORPAY = "RAZORPAY",
    PAYPAL = "PAYPAL",
};

export enum OtpPurpose {
  REGISTRATION = "REGISTRATION",
  PASSWORD_RESET = "PASSWORD_RESET",
};

export enum NotificationType {
  BOOKING_CONFIRMED = "BOOKING_CONFIRMED",
  BOOKING_CANCELLED = "BOOKING_CANCELLED",
  BOOKING_RESCHEDULED = "BOOKING_RESCHEDULED",
  BOOKING_REJECTED = "BOOKING_REJECTED",
  BOOKING_NOT_ATTENDED = "BOOKING_NOT_ATTENDED",
  BOOKING_APPROVED = "BOOKING_APPROVED",

  APPOINTMENT_CREATED = "APPOINTMENT_CREATED",
  APPOINTMENT_CANCELLED = "APPOINTMENT_CANCELLED",
  APPOINTMENT_RESCHEDULED = "APPOINTMENT_RESCHEDULED",
  APPOINTMENT_NOT_ATTENDED = "APPOINTMENT_NOT_ATTENDED",

  PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
  PAYMENT_FAILED = "PAYMENT_FAILED",

  SUBSCRIPTION_EXPIRING = "SUBSCRIPTION_EXPIRING",
  SUBSCRIPTION_EXPIRED = "SUBSCRIPTION_EXPIRED",

  BOOKING = "BOOKING",
  APPOINTMENT = "APPOINTMENT",

  SYSTEM = "SYSTEM",
};

export enum CalendarStatus {
    PENDING = "PENDING",
    CREATED = "CREATED",
    FAILED = "FAILED",
}


export enum EventStatus {
    SUCCESS = "SUCCESS",
    FAILED = "FAILED",
    PENDING = "PENDING",
    RETRY = "RETRY",
}