export enum PlanName {
  TRIAL = "TRIAL",
  STARTER = "STARTER",
  PROFESSIONAL = "PROFESSIONAL",
  ENTERPRISE = "ENTERPRISE",
  NO_SUBSCRIPTION = "NO_SUBSCRIPTION"
};

export enum StripeSyncStatus {
    PENDING = "PENDING",
    SYNCED = "SYNCED",
}